### ISSUE TITLE
error: source is required

### ISSUE THREAD

**Issue by bwanaaa** [saturnism/deepdream-cli-docker#3]
i copied an image file (Image00001.jpg) to the working directory that powershell uses

`C:\Users\Stefan.DESKTOP-QQLBN9D>`

Then I issued:

`cat Image00001.jpg | docker run -i saturnism/deepdream-cli-gcs > output.jpg`

and i get the above error

when i run 

`cat Image00001.jpg | docker run -i saturnism/deepdream-cli > output.jpg`

I get

```
Traceback (most recent call last):
  File "./deepdream.py", line 134, in <module>
    img = np.float32(PIL.Image.open(StringIO(sys.stdin.read())))
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 2028, in open
    raise IOError("cannot identify image file")
IOError: cannot identify image file
```

help?

**Comment by saturnism** [comment]
hiya, i don't have windows machine, but i'm not sure if windows has `cat` command. could i trouble you to check?

**Comment by bwanaaa** [comment]
powershell does
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\Stefan> cat

cmdlet Get-Content at command pipeline position 1
Supply values for the following parameters:
Path[0]:
```


Maybe I have to mount the volume of windows (path of image?) in the docker container?

**Comment by saturnism** [comment]
how abt `get-content -encoding byte` ?

the issue is potentially that the command didn't produce the right output to be piped to the container.

the `saturnism/deepdream-cli-gcs` takes in a `source` argument that's the location of the image on google cloud storage. so piping into that won't work either.
